name: Lattice label set

# The full label taxonomy for the Lattice repo. Applied to issues and PRs.
# These are created by `gh label create` during repo init.

# --- type: what kind of work is this? ---
- name: "type: feature"
  color: "1f883d"
  description: "A new user-facing capability"
- name: "type: bug"
  color: "d73a4a"
  description: "Something is broken, wrong, or surprising"
- name: "type: research"
  color: "5319e7"
  description: "A research question that needs an answer"
- name: "type: chore"
  color: "cccccc"
  description: "Maintenance, refactor, or non-feature work"
- name: "type: docs"
  color: "0075ca"
  description: "Documentation only"

# --- epic: which part of Lattice does this belong to? ---
- name: "epic: foundation"
  color: "fbca04"
  description: "Repo hygiene, CI, tooling — the team can work"
- name: "epic: tool-surface"
  color: "fbca04"
  description: "The 14 WebMCP tools and their schemas"
- name: "epic: workspace-ui"
  color: "fbca04"
  description: "The main workspace UI: paper list, PDF viewer, agent rail"
- name: "epic: agent-experience"
  color: "fbca04"
  description: "The agent rail, tool call log, confirmations, fallbacks"
- name: "epic: workflow-trail"
  color: "fbca04"
  description: "The killer feature: reviewable, replayable audit log"
- name: "epic: peer-review"
  color: "fbca04"
  description: "Cross-agent peer-reviewer demo (the exposedTo use case)"
- name: "epic: pdf-pipeline"
  color: "fbca04"
  description: "PDF ingestion, text extraction, two-column read order"
- name: "epic: bibliography"
  color: "fbca04"
  description: "CSL JSON, BibTeX, RIS export; arXiv/OpenAlex integration"
- name: "epic: design-system"
  color: "fbca04"
  description: "Tokens, type, motion, color, component library"
- name: "epic: landing-page"
  color: "fbca04"
  description: "The marketing landing page (the hero demo video)"
- name: "epic: demo-and-submit"
  color: "fbca04"
  description: "Demo video, README, submission form, deadline Sep 3"
- name: "epic: ops"
  color: "fbca04"
  description: "Deploys, secrets, observability, monitoring"

# --- priority ---
- name: "priority: critical"
  color: "b60205"
  description: "Blocker. Demo cannot ship without it."
- name: "priority: high"
  color: "d93f0b"
  description: "Directly affects a judging criterion"
- name: "priority: medium"
  color: "fbca04"
  description: "Important but not blocking"
- name: "priority: low"
  color: "cccccc"
  description: "Polish, nice-to-have"

# --- area: which technical area ---
- name: "area: webmcp"
  color: "0e8a16"
  description: "WebMCP API surface, tool registration, annotations"
- name: "area: pdf"
  color: "0e8a16"
  description: "PDF parsing, text extraction, layout analysis"
- name: "area: ai"
  color: "0e8a16"
  description: "LLM calls, prompt engineering, response handling"
- name: "area: storage"
  color: "0e8a16"
  description: "Netlify Blobs, persistence, migrations"
- name: "area: auth"
  color: "0e8a16"
  description: "Auth, sessions, rate limits, abuse"
- name: "area: deploy"
  color: "0e8a16"
  description: "netlify.toml, env, CI/CD"
- name: "area: design"
  color: "0e8a16"
  description: "Tokens, components, motion, accessibility"
- name: "area: content"
  color: "0e8a16"
  description: "Sample papers, copy, README, submission text"

# --- status ---
- name: "needs-triage"
  color: "ededed"
  description: "Issue has not been reviewed for priority/area"
- name: "in-progress"
  color: "1d76db"
  description: "Someone is actively working this"
- name: "blocked"
  color: "b60205"
  description: "Cannot proceed; see comments for the blocker"
- name: "ready-for-review"
  color: "0e8a16"
  description: "PR is ready, all checks green"
