/**
 * Workflow trail — the audit log of every tool call the agent has made.
 *
 * Persists to localStorage so the trail survives a page reload (a judge
 * who re-opens the demo sees the audit). The magic-link auth upgrade
 * will move this to Netlify Blobs keyed by the user.
 *
 * Each step records: timestamp, tool name, args, result summary, full
 * result, model interpretation, duration, status. The methods-appendix
 * exporter (#48) reads this directly.
 */

export interface WorkflowStep {
  step_id: number;
  timestamp: string;
  tool_name: string;
  args: unknown;
  result_summary: string;
  result_full: unknown;
  model_interpretation?: string;
  duration_ms: number;
  status: 'ok' | 'err' | 'denied';
}

export interface WorkflowSession {
  session_id: string;
  created_at: string;
  user_id: string;
  steps: WorkflowStep[];
}

const STORAGE_KEY = 'lattice.workflow-trail.v1';
const SESSION_KEY = 'lattice.workflow-trail.session.v1';

function getSessionId(): string {
  if (typeof localStorage === 'undefined') return 'session_unknown';
  let id = localStorage.getItem(SESSION_KEY);
  if (!id) {
    id = `sess_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
    localStorage.setItem(SESSION_KEY, id);
  }
  return id;
}

function readSession(): WorkflowSession {
  if (typeof localStorage === 'undefined') {
    return { session_id: 'session_unknown', created_at: new Date().toISOString(), user_id: 'anon', steps: [] };
  }
  const raw = localStorage.getItem(STORAGE_KEY);
  if (!raw) {
    const fresh: WorkflowSession = {
      session_id: getSessionId(),
      created_at: new Date().toISOString(),
      user_id: 'anon',
      steps: [],
    };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(fresh));
    return fresh;
  }
  try {
    return JSON.parse(raw) as WorkflowSession;
  } catch {
    return { session_id: getSessionId(), created_at: new Date().toISOString(), user_id: 'anon', steps: [] };
  }
}

function writeSession(session: WorkflowSession): void {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
}

export function recordStep(step: Omit<WorkflowStep, 'step_id' | 'timestamp' | 'session_id'>): WorkflowStep {
  const session = readSession();
  const fullStep: WorkflowStep = {
    step_id: session.steps.length + 1,
    timestamp: new Date().toISOString(),
    ...step,
  };
  session.steps.push(fullStep);
  writeSession(session);
  return fullStep;
}

export function getSession(): WorkflowSession {
  return readSession();
}

export function resetSession(): void {
  if (typeof localStorage !== 'undefined') {
    localStorage.removeItem(STORAGE_KEY);
  }
}

export function toMarkdownAppendix(session: WorkflowSession): string {
  const lines: string[] = [
    '# AI-assisted methods appendix',
    '',
    `Generated by Lattice on ${new Date(session.created_at).toISOString()}.`,
    '',
    '## Session',
    '',
    `- Session ID: \`${session.session_id}\``,
    `- Steps: ${session.steps.length}`,
    '',
    '## Steps',
    '',
    ...session.steps.flatMap((s) => [
      `### Step ${s.step_id} — \`${s.tool_name}\` (${s.status})`,
      '',
      `- Timestamp: ${s.timestamp}`,
      `- Duration: ${s.duration_ms}ms`,
      '',
      'Args:',
      '',
      '```json',
      JSON.stringify(s.args, null, 2),
      '```',
      '',
      'Result:',
      '',
      '```',
      s.result_summary.slice(0, 1000),
      '```',
      '',
    ]),
  ];
  return lines.join('\n');
}
